program Sistema;

uses
  Forms,
  UMenuPrin in 'UMenuPrin.pas' {fMenuPrin},
  UDMBanco in 'UDMBanco.pas' {DmBanco: TDataModule},
  UDM in 'UDM.pas' {DM: TDataModule},
  UCidade in 'UCidade.pas' {fCidade},
  UUtil in 'UUtil.pas',
  UEmpresa in 'UEmpresa.pas' {fEmpresa},
  UPesquisa in 'UPesquisa.pas' {fPesquisa},
  ULocal in 'ULocal.pas' {fLocal},
  UResp in 'UResp.pas' {fResp},
  UResultado in 'UResultado.pas' {fResultado},
  UManutencao in 'UManutencao.pas' {fManutencao},
  UMarca in 'UMarca.pas' {fMarca},
  UPeca in 'UPeca.pas' {fPeca},
  UObs in 'UObs.pas' {fObs},
  UVendedor in 'UVendedor.pas' {fVendedor},
  ULote in 'ULote.pas' {fLote},
  UPessoa in 'UPessoa.pas' {fPessoa},
  UPesqSelo in 'UPesqSelo.pas' {fPesqSelo},
  UTabControle in 'UTabControle.pas' {fTabControle},
  UAgente in 'UAgente.pas' {fAgente},
  UCliExtintor in 'UCliExtintor.pas' {fCliExtintor},
  UNovoExtintor in 'UNovoExtintor.pas' {fNovoExtintor},
  UCapacidade in 'UCapacidade.pas' {fCapacidade},
  UJProposta in 'UJProposta.pas' {fjProposta},
  UItensOrdem in 'UItensOrdem.pas' {fItensOrdem},
  UOrdem in 'UOrdem.pas' {fOrdem},
  UTabPeca in 'UTabPeca.pas' {fTabPeca},
  UROrdemServico2 in 'UROrdemServico2.pas' {fROrdemServico2},
  UICliExtintor in 'UICliExtintor.pas' {fICliExtintor},
  UrCliExtintor_2 in 'UrCliExtintor_2.pas' {frCliExtintor_2},
  UISelo in 'UISelo.pas' {fISelo},
  URSelo in 'URSelo.pas' {FrSelo},
  UIVencimento in 'UIVencimento.pas' {fIVencimento},
  URVencimento in 'URVencimento.pas' {FrVencimento},
  UrResVencimento in 'UrResVencimento.pas' {FrResVencimento},
  UIOrdem in 'UIOrdem.pas' {fIOrdem},
  UROrdem in 'UROrdem.pas' {frOrdem},
  UILote in 'UILote.pas' {fILote},
  UExtratoEstoque in 'UExtratoEstoque.pas' {fExtratoEstoque},
  UCompra in 'UCompra.pas' {fCompra},
  UItensCompra in 'UItensCompra.pas' {fItensCompra},
  UMedida in 'UMedida.pas' {fMedida},
  UCliente in 'UCliente.pas' {fCliente},
  UItemExtintor in 'UItemExtintor.pas' {fItemExtintor},
  UMovimento in 'UMovimento.pas' {fMovimento},
  UItensMovimento in 'UItensMovimento.pas' {fItensMovimento},
  UIRastro in 'UIRastro.pas' {fIRastro},
  URRastro in 'URRastro.pas' {FrRastro},
  Uproposta in 'Uproposta.pas' {fProposta},
  UItensProposta in 'UItensProposta.pas' {fItensProposta},
  UTabPreco in 'UTabPreco.pas' {fTabPreco},
  URProposta in 'URProposta.pas' {FrProposta},
  UJOrdem in 'UJOrdem.pas' {fjOrdem},
  UJCompra in 'UJCompra.pas' {fJCompra},
  UParametros in 'UParametros.pas' {fParametros},
  UDMR in 'UDMR.pas' {DMR: TDataModule},
  UClServico in 'UClServico.pas',
  UUtilServico in 'UUtilServico.pas' {fUtilServico},
  USenha in 'USenha.pas' {fSenha},
  UUsuario in 'UUsuario.pas' {fUsuario},
  UJUsuario in 'UJUsuario.pas' {fJUsuario},
  UAleraSenha in 'UAleraSenha.pas' {fAlteraSenha},
  UTrocaSelo in 'UTrocaSelo.pas' {fTrocaSelo},
  UIntervaloSelo in 'UIntervaloSelo.pas' {fIntervaloSelo},
  UClasItensServico in 'UClasItensServico.pas',
  UIOrdemServico in 'UIOrdemServico.pas' {fIOrdemServico},
  UClasServicoNegocio in 'UClasServicoNegocio.pas',
  UClasConexao in 'UClasConexao.pas',
  uClasBairro in 'uClasBairro.pas',
  uClasCidade in 'uClasCidade.pas',
  uClasPessoa in 'uClasPessoa.pas',
  uClasBairroServico in 'uClasBairroServico.pas',
  uClasCidadeServico in 'uClasCidadeServico.pas',
  uPessoaServico in 'uPessoaServico.pas',
  UfrmClienteImportar in 'UfrmClienteImportar.pas' {frmClienteImportar},
  UBairro in 'UBairro.pas' {fBairro},
  UdmPessoa in 'UdmPessoa.pas' {dmPessoa: TDataModule},
  Vcl.Themes,
  Vcl.Styles,
  uEtiqueta in 'uEtiqueta.pas' {fEtiqueta},
  uTrataGrid in 'uTrataGrid.pas',
  uClassReportBuilder in 'uClassReportBuilder.pas',
  ufrmCodigoBarras in 'ufrmCodigoBarras.pas' {frmCodigoBarras},
  udmParametro in 'udmParametro.pas' {dmParametro: TDataModule},
  UrOrdemServicoI in 'UrOrdemServicoI.pas' {frOrdemServicoI},
  UROrdemServicoInspecao in 'UROrdemServicoInspecao.pas' {fROrdemServicoInspecao},
  UROrdemServico in 'UROrdemServico.pas' {fROrdemServico1},
  uVersao in 'uVersao.pas',
  UAbout in 'UAbout.pas' {frmAbout},
  uclassCapacidade in 'uclassCapacidade.pas',
  UrCliExtintor in 'UrCliExtintor.pas' {frCliExtintor},
  UdmOrdemServico in 'UdmOrdemServico.pas' {dmOrdemServico: TDataModule},
  uManutencaoController in 'uManutencaoController.pas',
  UOSCliente in 'UOSCliente.pas' {frmOSCliente},
  uImpressaoOrdemServico in 'uImpressaoOrdemServico.pas' {frmImpressaoOrdemServico},
  URCliExtintor_3 in 'URCliExtintor_3.pas' {frCliExtintor_3},
  uArgox in 'uArgox.pas';

{$R *.res}

begin
  Application.Initialize;
  TStyleManager.TrySetStyle('Aqua Light Slate');
  Application.CreateForm(TfSenha, fSenha);
  Application.CreateForm(TfMenuPrin, fMenuPrin);
  Application.CreateForm(TDmBanco, DmBanco);
  Application.CreateForm(TDM, DM);
  Application.CreateForm(TDMR, DMR);
  Application.Run;
end.
