unit UROrdem;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, FMTBcd, ppBands, ppDB, ppDBPipe, ppCtrls, ppClass, ppVar,
  ppPrnabl, ppCache, ppComm, ppRelatv, ppProd, ppReport, DBClient, DB,
  Provider, SqlExpr, ppViewr, ppStrtch, ppSubRpt, ppMemo, ppParameter,
  ppDesignLayer;

type
  TfrOrdem = class(TForm)
    Qordem: TSQLQuery;
    dspOrdem: TDataSetProvider;
    dsOrdem: TDataSource;
    Ordem: TClientDataSet;
    RelOrdem: TppReport;
    ppHeaderBand1: TppHeaderBand;
    ppLabel14: TppLabel;
    ppLabel15: TppLabel;
    ppLabel16: TppLabel;
    ppLabel18: TppLabel;
    ppLabel19: TppLabel;
    ppLabel20: TppLabel;
    ppLabel21: TppLabel;
    ppLabel22: TppLabel;
    ppLabel23: TppLabel;
    ppLabel24: TppLabel;
    ppLabel25: TppLabel;
    ppLabel26: TppLabel;
    ppLabel27: TppLabel;
    ppLabel28: TppLabel;
    ppLabel29: TppLabel;
    ppLabel35: TppLabel;
    ppLabel79: TppLabel;
    ppLine1: TppLine;
    ppLabel30: TppLabel;
    ppLabel32: TppLabel;
    ppLabel33: TppLabel;
    ppSystemVariable1: TppSystemVariable;
    ppSystemVariable2: TppSystemVariable;
    ppSystemVariable3: TppSystemVariable;
    ppLabel4: TppLabel;
    ppLabel5: TppLabel;
    lblData: TppLabel;
    ppDetailBand1: TppDetailBand;
    ppDBText11: TppDBText;
    ppDBText12: TppDBText;
    ppDBText13: TppDBText;
    ppDBText14: TppDBText;
    ppDBText15: TppDBText;
    ppDBText16: TppDBText;
    ppDBText17: TppDBText;
    ppDBText18: TppDBText;
    ppDBText19: TppDBText;
    ppDBText20: TppDBText;
    ppDBText21: TppDBText;
    ppDBText22: TppDBText;
    ppDBText23: TppDBText;
    ppDBText25: TppDBText;
    ppDBText28: TppDBText;
    ppDBText33: TppDBText;
    ppDBText24: TppDBText;
    ppDBText26: TppDBText;
    ppDBText27: TppDBText;
    ppGroup1: TppGroup;
    ppGroupHeaderBand1: TppGroupHeaderBand;
    ppLabel2: TppLabel;
    ppDBText2: TppDBText;
    ppGroupFooterBand1: TppGroupFooterBand;
    ppLine2: TppLine;
    ppLabel7: TppLabel;
    ppDBCalc2: TppDBCalc;
    ppGroup2: TppGroup;
    ppGroupHeaderBand2: TppGroupHeaderBand;
    ppLabel1: TppLabel;
    ppDBText1: TppDBText;
    ppDBText3: TppDBText;
    ppDBText4: TppDBText;
    ppLabel3: TppLabel;
    ppGroupFooterBand2: TppGroupFooterBand;
    ppDBCalc1: TppDBCalc;
    ppLine3: TppLine;
    ppLabel6: TppLabel;
    dbOrdem: TppDBPipeline;
    ppSummaryBand1: TppSummaryBand;
    ppLabel8: TppLabel;
    ppDBCalc3: TppDBCalc;
    ppDBText5: TppDBText;
    ppLabel9: TppLabel;
    OrdemDATAORDEM: TSQLTimeStampField;
    OrdemNOME: TStringField;
    OrdemCODPESSOA: TFloatField;
    OrdemNUMERO: TFloatField;
    OrdemNUMORDEM: TFloatField;
    OrdemCODMARCA: TFloatField;
    OrdemCAPACIDADE: TStringField;
    OrdemANO: TSmallintField;
    OrdemSERIE: TStringField;
    OrdemPRESTRABALHO: TStringField;
    OrdemPRESENSAIO: TStringField;
    OrdemPESOVAZIO: TStringField;
    OrdemPESOCHEIO: TStringField;
    OrdemVOLUME: TStringField;
    OrdemCAPACMAXIMA: TStringField;
    OrdemDVM: TStringField;
    OrdemDVB: TStringField;
    OrdemCODRESULTADO: TFloatField;
    OrdemCODNIVEL: TFloatField;
    OrdemCODAGENTE: TFloatField;
    OrdemULTIMOSELO: TFloatField;
    OrdemLOTE: TStringField;
    OrdemOUTROSELO: TFloatField;
    OrdemNUMSELO: TFloatField;
    OrdemCODRESP: TStringField;
    OrdemPESO: TFloatField;
    OrdemTIPO: TStringField;
    OrdemDESCMARCA: TStringField;
    QordemDATAORDEM: TSQLTimeStampField;
    QordemNOME: TStringField;
    QordemCODPESSOA: TFloatField;
    QordemNUMERO: TFloatField;
    QordemNUMORDEM: TFloatField;
    QordemCODMARCA: TFloatField;
    QordemCAPACIDADE: TStringField;
    QordemANO: TSmallintField;
    QordemSERIE: TStringField;
    QordemPRESTRABALHO: TStringField;
    QordemPRESENSAIO: TStringField;
    QordemPESOVAZIO: TStringField;
    QordemPESOCHEIO: TStringField;
    QordemVOLUME: TStringField;
    QordemCAPACMAXIMA: TStringField;
    QordemDVM: TStringField;
    QordemDVB: TStringField;
    QordemCODRESULTADO: TFloatField;
    QordemCODNIVEL: TFloatField;
    QordemCODAGENTE: TFloatField;
    QordemULTIMOSELO: TFloatField;
    QordemLOTE: TStringField;
    QordemOUTROSELO: TFloatField;
    QordemNUMSELO: TFloatField;
    QordemCODRESP: TStringField;
    QordemPESO: TFloatField;
    QordemTIPO: TStringField;
    QordemDESCMARCA: TStringField;
    QordemCODCAPACIDADE: TIntegerField;
    OrdemCODCAPACIDADE: TIntegerField;
    Memo: TppMemo;
    OrdemC_QTDETIPO: TFloatField;
    ppLabel10: TppLabel;
    ppDBText6: TppDBText;
    ppDBCalc4: TppDBCalc;
    QordemPERCENTUAL: TStringField;
    OrdemPERCENTUAL: TStringField;
    ppLabel11: TppLabel;
    ppDBText7: TppDBText;
    Qresumo: TSQLQuery;
    dspResumo: TDataSetProvider;
    Resumo: TClientDataSet;
    dsResumo: TDataSource;
    dbResumo: TppDBPipeline;
    RelResumo: TppReport;
    ppHeaderBand2: TppHeaderBand;
    ppDetailBand2: TppDetailBand;
    ppLabel12: TppLabel;
    ppGroup3: TppGroup;
    ppGroupHeaderBand3: TppGroupHeaderBand;
    ppGroupFooterBand3: TppGroupFooterBand;
    ppDBText8: TppDBText;
    ppGroup4: TppGroup;
    ppGroupHeaderBand4: TppGroupHeaderBand;
    ppGroupFooterBand4: TppGroupFooterBand;
    ppLabel13: TppLabel;
    ppDBText9: TppDBText;
    ppDBText10: TppDBText;
    ppDBText29: TppDBText;
    ppDBText30: TppDBText;
    ppSummaryBand2: TppSummaryBand;
    ppLabel17: TppLabel;
    ppSystemVariable4: TppSystemVariable;
    ppSystemVariable5: TppSystemVariable;
    ppSystemVariable6: TppSystemVariable;
    lblData1: TppLabel;
    ppLabel31: TppLabel;
    ppLabel34: TppLabel;
    ppLabel36: TppLabel;
    ppLine4: TppLine;
    ppLine5: TppLine;
    ppDBCalc5: TppDBCalc;
    ppDBCalc6: TppDBCalc;
    ppDBText31: TppDBText;
    ppLine7: TppLine;
    ppLabel37: TppLabel;
    ppLabel38: TppLabel;
    ppDBText35: TppDBText;
    ppDBText36: TppDBText;
    ppDBCalc7: TppDBCalc;
    ppDBCalc8: TppDBCalc;
    ppDBCalc9: TppDBCalc;
    ppDBCalc10: TppDBCalc;
    ppLabel39: TppLabel;
    ppLine6: TppLine;
    ppLabel40: TppLabel;
    ppLabel41: TppLabel;
    ppLabel42: TppLabel;
    ppLabel43: TppLabel;
    lblSeloIni: TppLabel;
    lblSeloFin: TppLabel;
    lblServIni: TppLabel;
    lblServFin: TppLabel;
    QIni: TSQLQuery;
    QtdeSelos: TSQLQuery;
    QtdeSelosQTDE: TIntegerField;
    ppLabel44: TppLabel;
    lblQtdeSelos: TppLabel;
    QIniNUMORDEM: TFloatField;
    QIniNUMSELO: TFloatField;
    QIniMAX_NUMORDEM: TFloatField;
    QIniMAX_NUMSELO: TFloatField;
    Rel3: TppReport;
    ppHeaderBand3: TppHeaderBand;
    ppDetailBand3: TppDetailBand;
    ppDBText32: TppDBText;
    ppDBText34: TppDBText;
    ppDBText37: TppDBText;
    ppDBCalc11: TppDBCalc;
    ppSummaryBand3: TppSummaryBand;
    SQLQuery1: TSQLQuery;
    RelOrdem1: TppReport;
    ppParameterList4: TppParameterList;
    ppDesignLayers4: TppDesignLayers;
    ppDesignLayer4: TppDesignLayer;
    ppHeaderBand4: TppHeaderBand;
    ppDetailBand4: TppDetailBand;
    ppLabel45: TppLabel;
    lblData01: TppLabel;
    ppSystemVariable7: TppSystemVariable;
    ppSystemVariable8: TppSystemVariable;
    ppSystemVariable9: TppSystemVariable;
    ppLabel47: TppLabel;
    ppLabel48: TppLabel;
    ppLabel49: TppLabel;
    ppLabel50: TppLabel;
    ppLabel51: TppLabel;
    ppLabel52: TppLabel;
    ppLabel53: TppLabel;
    ppLabel54: TppLabel;
    ppLabel55: TppLabel;
    ppLabel56: TppLabel;
    ppLabel57: TppLabel;
    ppLabel58: TppLabel;
    ppLabel59: TppLabel;
    ppLabel60: TppLabel;
    ppLabel61: TppLabel;
    ppLabel62: TppLabel;
    ppLabel63: TppLabel;
    ppLabel64: TppLabel;
    ppLine8: TppLine;
    ppLabel65: TppLabel;
    ppLabel66: TppLabel;
    ppLabel67: TppLabel;
    ppLabel68: TppLabel;
    ppLabel69: TppLabel;
    ppLabel70: TppLabel;
    ppGroup5: TppGroup;
    ppGroupHeaderBand5: TppGroupHeaderBand;
    ppGroupFooterBand5: TppGroupFooterBand;
    ppLabel46: TppLabel;
    ppDBText38: TppDBText;
    ppGroup6: TppGroup;
    ppGroupHeaderBand6: TppGroupHeaderBand;
    ppGroupFooterBand6: TppGroupFooterBand;
    ppLabel71: TppLabel;
    ppLabel72: TppLabel;
    ppDBText39: TppDBText;
    ppDBText40: TppDBText;
    ppDBText41: TppDBText;
    ppDBText42: TppDBText;
    ppDBText43: TppDBText;
    ppDBText44: TppDBText;
    ppDBText45: TppDBText;
    ppDBText46: TppDBText;
    ppDBText47: TppDBText;
    ppDBText48: TppDBText;
    ppDBText49: TppDBText;
    ppDBText50: TppDBText;
    ppDBText51: TppDBText;
    ppDBText52: TppDBText;
    ppDBText53: TppDBText;
    ppDBText54: TppDBText;
    ppDBText55: TppDBText;
    ppDBText56: TppDBText;
    ppDBText57: TppDBText;
    ppDBText58: TppDBText;
    ppDBText59: TppDBText;
    ppDBText60: TppDBText;
    ppDBText61: TppDBText;
    ppDBText62: TppDBText;
    ppDBText63: TppDBText;
    ppLine9: TppLine;
    ppLabel73: TppLabel;
    ppDBCalc12: TppDBCalc;
    ppLabel74: TppLabel;
    ppDBCalc13: TppDBCalc;
    ppSummaryBand4: TppSummaryBand;
    ppLabel75: TppLabel;
    ppDBCalc14: TppDBCalc;
    Memo01: TppMemo;
    procedure RelOrdemPreviewFormCreate(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  frOrdem: TfrOrdem;

implementation

uses UDMBanco;


{$R *.dfm}

procedure TfrOrdem.RelOrdemPreviewFormCreate(Sender: TObject);
begin
   TPPReport(Sender).PreviewForm.WindowState:=wsMaximized;
   TPPViewer(TPPReport(Sender).PreviewForm.Viewer).ZoomPercentage:=90;
end;

end.
